[package]
name = "cqcwrappers"
version = "0.1.0"
authors = ["bart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cqc = "0.6"
cqc = { path = "../cqc" }
bincode = "1.2"